#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/dream/.vscode-server/cli/servers/Stable-488a1f239235055e34e673291fb8d8c810886f81/server/node" "/home/dream/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"